"""Full end-to-end workflow test:

citizen registers → submits report → uploads real video → FFmpeg thumbnail/frames
→ AI analyzes (in-process stub AI service) → classification stored → routing rule
selects organization → org staff logs in → accepts → in_progress → resolution
evidence → resolved → citizen sees resolution + notifications.

Also: AI-offline failure path and unauthorized-org access are covered in
test_state_machine.py / test_security.py.
"""
import io
import subprocess
import threading

import pytest

from app.db import SessionLocal
from app.models import Organization, OrganizationRule, OrganizationUser, Role, User
from app.security import hash_password
from tests.conftest import TestClient
from app.main import app


def _ffmpeg_ok():
    try:
        return subprocess.run(["ffmpeg", "-version"], capture_output=True, timeout=5).returncode == 0
    except Exception:
        return False


@pytest.fixture(scope="module")
def stub_ai(client):
    """Run the real AI service in-process on a free port and point the backend at it."""
    import sys, os
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "ai-service")))
    import uvicorn
    from main import app as ai_app

    config = uvicorn.Config(ai_app, host="127.0.0.1", port=18090, log_level="error")
    server = uvicorn.Server(config)
    th = threading.Thread(target=server.run, daemon=True)
    th.start()
    import time, httpx
    for _ in range(50):
        try:
            if httpx.get("http://127.0.0.1:18090/health", timeout=1).status_code == 200:
                break
        except Exception:
            time.sleep(0.1)
    from app import jobs as jobs_mod
    old = jobs_mod.settings.ai_service_url
    jobs_mod.settings.ai_service_url = "http://127.0.0.1:18090"
    yield
    jobs_mod.settings.ai_service_url = old
    server.should_exit = True


@pytest.mark.skipif(not _ffmpeg_ok(), reason="ffmpeg not available")
def test_full_citizen_to_resolution_flow(client, stub_ai, tmp_path):
    # --- setup: dedicated org + routing rule + org staff ---
    db = SessionLocal()
    org = Organization(name="E2E Roads Bureau", org_type="Roads/Public Works")
    db.add(org)
    db.commit()
    db.add(OrganizationRule(category="Roads & Transportation", organization_id=org.id,
                            priority=1, keywords="pothole,e2e"))
    staff = User(name="E2E Staff", email="e2estaff@test.et", role=Role.org_staff,
                 password_hash=hash_password("e2e-staff-pass"))
    db.add(staff)
    db.commit()
    db.add(OrganizationUser(organization_id=org.id, user_id=staff.id))
    db.commit()
    org_id = org.id
    db.close()

    # --- 1-2: citizen registers + logs in (register auto-logs-in) ---
    citizen = TestClient(app)
    r = citizen.post("/api/auth/register", json={
        "name": "E2E Citizen", "email": "e2ecitizen@test.et",
        "password": "e2e-citizen-pass", "city": "Addis Ababa", "language": "am"})
    assert r.status_code == 200

    # --- 3: submit report ---
    r = citizen.post("/api/reports", json={
        "title": "E2E deep pothole on main road",
        "description": "A deep dangerous e2e pothole affecting many cars near the school. Urgent!",
        "category": "Roads & Transportation", "city": "Addis Ababa",
        "latitude": 9.02, "longitude": 38.75, "address": "E2E Street"})
    assert r.status_code == 201
    rid = r.json()["id"]

    # --- 4: upload a REAL video (generated by ffmpeg) ---
    vid = tmp_path / "e2e.mp4"
    subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "testsrc=duration=2:size=320x240:rate=10",
                    "-c:v", "libx264", "-pix_fmt", "yuv420p", str(vid)],
                   capture_output=True, timeout=60)
    with open(vid, "rb") as f:
        up = citizen.post(f"/api/reports/{rid}/media",
                          files={"file": ("e2e.mp4", f, "video/mp4")})
    assert up.status_code == 201
    assert up.json()["has_thumb"] is True          # FFmpeg thumbnail worked

    # --- 5-8: finalize -> AI pipeline runs synchronously via direct job call ---
    from app.jobs import process_report
    process_report(rid)

    detail = citizen.get(f"/api/reports/{rid}").json()
    assert detail["ai"] is not None
    assert detail["ai"]["category"] == "Roads & Transportation"
    assert detail["ai"]["frames_analyzed"] >= 1     # frames actually reached the model
    assert detail["organization_name"] == "E2E Roads Bureau"
    assert detail["status"] in ("under_review", "assigned")

    # citizen got Amharic notifications
    notes = citizen.get("/api/notifications").json()
    assert any(n["kind"] == "analyzed" for n in notes)

    # --- 9-11: org staff sees + accepts it ---
    staff_c = TestClient(app)
    staff_c.post("/api/auth/login", json={"email": "e2estaff@test.et", "password": "e2e-staff-pass"})
    org_reports = staff_c.get("/api/dashboard/org-reports").json()
    assert rid in [x["id"] for x in org_reports]
    assert staff_c.patch(f"/api/reports/{rid}/assignment", json={"accept": True}).status_code == 200

    # --- 12: status to in_progress ---
    assert staff_c.patch(f"/api/reports/{rid}/status",
                         json={"status": "in_progress", "note": "Crew dispatched"}).status_code == 200

    # --- 13: resolution evidence ---
    png = io.BytesIO(b"\x89PNG\r\n\x1a\n" + b"fixedroad" * 30)
    res_up = staff_c.post(f"/api/reports/{rid}/media", data={"kind": "resolution"},
                          files={"file": ("fixed.png", png, "image/png")})
    assert res_up.status_code == 201

    # --- 14: resolve ---
    assert staff_c.patch(f"/api/reports/{rid}/status",
                         json={"status": "resolved", "note": "Pothole filled"}).status_code == 200

    # --- 15: citizen sees resolution + evidence + notification ---
    final = citizen.get(f"/api/reports/{rid}").json()
    assert final["status"] == "resolved"
    assert final["resolved_at"] is not None
    assert any(m["kind"] == "resolution" for m in final["media"])
    notes = citizen.get("/api/notifications").json()
    assert any(n["kind"] == "resolved" for n in notes)

    # timeline is complete and ordered
    statuses = [h["to_status"] for h in final["history"]]
    assert statuses[0] == "submitted" and statuses[-1] == "resolved"
    assert "in_progress" in statuses

    # --- bonus: citizen can dispute/reopen ---
    assert citizen.post(f"/api/reports/{rid}/reopen?reason=Not actually fixed").status_code == 200
    assert citizen.get(f"/api/reports/{rid}").json()["status"] == "reopened"

    # --- staff can view routing explanation? (staff-only endpoint, org_staff is not admin/mod) ---
    assert staff_c.get(f"/api/admin/reports/{rid}/routing").status_code == 403


def test_unmatched_routing_goes_to_manual(client, stub_ai):
    """Category with no routing rule -> needs_manual_routing, never lost."""
    r = client.post("/api/reports", json={
        "title": "River pollution near factory",
        "description": "Chemical smell and dark water in the river near the industrial zone.",
        "category": "Environment", "city": "Addis Ababa",
        "captcha_a": 2, "captcha_b": 2, "captcha_answer": 4})
    rid = r.json()["id"]
    from app.jobs import process_report
    process_report(rid)
    db = SessionLocal()
    from app.models import Report
    rpt = db.get(Report, rid)
    assert rpt.routing_state == "needs_manual_routing"
    assert rpt.status.value == "under_review"
    db.close()
