"""phase b: resolution verification, moderation, upload sessions, offline keys

Revision ID: 04f8c65cb564
Revises: 5ce1f3eaa5ef
Create Date: 2026-08-18 07:41:02.736131
"""
from alembic import op
import sqlalchemy as sa


revision = '04f8c65cb564'
down_revision = '5ce1f3eaa5ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('received', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_created_at'), 'upload_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_upload_sessions_report_id'), 'upload_sessions', ['report_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_status'), 'upload_sessions', ['status'], unique=False)
    op.add_column('report_comments', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    op.add_column('report_comments', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('resolution_confirmed', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('resolution_check_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('resolution_check_notes', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('client_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_reports_client_key'), 'reports', ['client_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_client_key'), table_name='reports')
    op.drop_column('reports', 'client_key')
    op.drop_column('reports', 'resolution_check_notes')
    op.drop_column('reports', 'resolution_check_score')
    op.drop_column('reports', 'resolution_confirmed')
    op.drop_column('report_comments', 'hidden')
    op.drop_column('report_comments', 'is_flagged')
    op.drop_index(op.f('ix_upload_sessions_status'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_report_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_created_at'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
