"""p1: departments, invites, mfa, email verification

Revision ID: 156f792574f9
Revises: 3429ac4056df
Create Date: 2026-08-18 08:44:03.657869
"""
from alembic import op
import sqlalchemy as sa


revision = '156f792574f9'
down_revision = '3429ac4056df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('email_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_table('staff_invites',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('org_role', sa.String(length=32), nullable=True),
    sa.Column('invited_by', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_staff_invites_email'), 'staff_invites', ['email'], unique=False)
    op.add_column('organization_users', sa.Column('department_id', sa.String(length=32), nullable=True))
    with op.batch_alter_table('organization_users') as batch_op:
        batch_op.create_foreign_key('fk_orgusers_dept', 'departments', ['department_id'], ['id'])
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mfa_backup_codes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'email_verified')
    with op.batch_alter_table('organization_users') as batch_op:
        batch_op.drop_constraint('fk_orgusers_dept', type_='foreignkey')
    op.drop_column('organization_users', 'department_id')
    op.drop_index(op.f('ix_staff_invites_email'), table_name='staff_invites')
    op.drop_table('staff_invites')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
