"""phase c: subscriptions, community votes, geo routing, notif prefs

Revision ID: 3429ac4056df
Revises: 04f8c65cb564
Create Date: 2026-08-18 08:15:41.718600
"""
from alembic import op
import sqlalchemy as sa


revision = '3429ac4056df'
down_revision = '04f8c65cb564'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('community_votes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('vote', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id')
    )
    op.create_index(op.f('ix_community_votes_report_id'), 'community_votes', ['report_id'], unique=False)
    op.create_index(op.f('ix_community_votes_user_id'), 'community_votes', ['user_id'], unique=False)
    op.add_column('organization_rules', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('organization_rules', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('organization_rules', sa.Column('radius_m', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('notif_prefs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notif_prefs')
    op.drop_column('organization_rules', 'radius_m')
    op.drop_column('organization_rules', 'longitude')
    op.drop_column('organization_rules', 'latitude')
    op.drop_index(op.f('ix_community_votes_user_id'), table_name='community_votes')
    op.drop_index(op.f('ix_community_votes_report_id'), table_name='community_votes')
    op.drop_table('community_votes')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
