"""civiclens 2.0: ai reviews, clusters, sla, escalations, evidence integrity

Revision ID: 5ce1f3eaa5ef
Revises: a9f64836b730
Create Date: 2026-08-18 07:19:48.422405
"""
from alembic import op
import sqlalchemy as sa


revision = '5ce1f3eaa5ef'
down_revision = 'a9f64836b730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('issue_clusters',
        sa.Column('id', sa.String(length=32), primary_key=True),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('category', sa.String(length=64)),
        sa.Column('city', sa.String(length=64)),
        sa.Column('latitude', sa.Float()),
        sa.Column('longitude', sa.Float()),
        sa.Column('severity', sa.Integer()),
        sa.Column('report_count', sa.Integer()),
        sa.Column('unique_reporters', sa.Integer()),
        sa.Column('first_reported', sa.DateTime(timezone=True)),
        sa.Column('last_reported', sa.DateTime(timezone=True)),
        sa.Column('status', sa.String(length=32)),
        sa.Column('created_at', sa.DateTime(timezone=True)))
    op.create_index('ix_issue_clusters_category', 'issue_clusters', ['category'])
    op.create_index('ix_issue_clusters_city', 'issue_clusters', ['city'])
    op.create_index('ix_issue_clusters_status', 'issue_clusters', ['status'])
    op.create_table('ai_reviews',
        sa.Column('id', sa.String(length=32), primary_key=True),
        sa.Column('report_id', sa.String(length=32), sa.ForeignKey('reports.id'), nullable=False),
        sa.Column('analysis_id', sa.String(length=32), sa.ForeignKey('report_ai_analysis.id')),
        sa.Column('reason', sa.String(length=32), nullable=False),
        sa.Column('detail', sa.Text()),
        sa.Column('status', sa.String(length=16)),
        sa.Column('reviewer_id', sa.String(length=32), sa.ForeignKey('users.id')),
        sa.Column('decided_at', sa.DateTime(timezone=True)),
        sa.Column('corrected_category', sa.String(length=64)),
        sa.Column('corrected_severity', sa.Integer()),
        sa.Column('decision_reason', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True)))
    op.create_index('ix_ai_reviews_report_id', 'ai_reviews', ['report_id'])
    op.create_index('ix_ai_reviews_reason', 'ai_reviews', ['reason'])
    op.create_index('ix_ai_reviews_status', 'ai_reviews', ['status'])
    op.create_table('sla_policies',
        sa.Column('id', sa.String(length=32), primary_key=True),
        sa.Column('organization_id', sa.String(length=32), sa.ForeignKey('organizations.id')),
        sa.Column('min_severity', sa.Integer()),
        sa.Column('ack_hours', sa.Integer(), nullable=False),
        sa.Column('resolve_hours', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True)))
    op.create_table('escalation_events',
        sa.Column('id', sa.String(length=32), primary_key=True),
        sa.Column('report_id', sa.String(length=32), sa.ForeignKey('reports.id'), nullable=False),
        sa.Column('organization_id', sa.String(length=32), sa.ForeignKey('organizations.id')),
        sa.Column('kind', sa.String(length=24), nullable=False),
        sa.Column('overdue_hours', sa.Float()),
        sa.Column('notified', sa.Boolean()),
        sa.Column('created_at', sa.DateTime(timezone=True)))
    op.create_index('ix_escalation_events_report_id', 'escalation_events', ['report_id'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_media', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('report_media', sa.Column('phash', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_report_media_phash'), 'report_media', ['phash'], unique=False)
    op.create_index(op.f('ix_report_media_sha256'), 'report_media', ['sha256'], unique=False)
    op.add_column('reports', sa.Column('cluster_id', sa.String(length=32), nullable=True))
    op.add_column('reports', sa.Column('integrity_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('integrity_notes', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_reports_cluster_id'), 'reports', ['cluster_id'], unique=False)
    with op.batch_alter_table('reports') as batch_op:
        batch_op.create_foreign_key('fk_reports_cluster', 'issue_clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('escalation_events')
    op.drop_table('sla_policies')
    op.drop_table('ai_reviews')
    op.drop_table('issue_clusters')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports') as batch_op:
        batch_op.drop_constraint('fk_reports_cluster', type_='foreignkey')
    op.drop_index(op.f('ix_reports_cluster_id'), table_name='reports')
    op.drop_column('reports', 'acknowledged_at')
    op.drop_column('reports', 'integrity_notes')
    op.drop_column('reports', 'integrity_score')
    op.drop_column('reports', 'cluster_id')
    op.drop_index(op.f('ix_report_media_sha256'), table_name='report_media')
    op.drop_index(op.f('ix_report_media_phash'), table_name='report_media')
    op.drop_column('report_media', 'phash')
    op.drop_column('report_media', 'sha256')
    # ### end Alembic commands ###
