"""hardening: csrf sessions, lockout, password reset, jobs, state machine, routing metadata

Revision ID: fd70736190d2
Revises: 68b7c8092467
Create Date: 2026-08-17 17:58:08.179028
"""
from alembic import op
import sqlalchemy as sa


revision = 'fd70736190d2'
down_revision = '68b7c8092467'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_ai_analysis', sa.Column('analyzer', sa.String(length=64), nullable=True))
    op.add_column('report_ai_analysis', sa.Column('input_kind', sa.String(length=64), nullable=True))
    op.add_column('report_ai_analysis', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('report_ai_analysis', sa.Column('success', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('routing_state', sa.String(length=32), nullable=True))
    op.add_column('reports', sa.Column('routed_rule_id', sa.String(length=32), nullable=True))
    op.add_column('reports', sa.Column('processing_state', sa.String(length=32), nullable=True))
    op.add_column('reports', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('human_confirmed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_reports_routing_state'), 'reports', ['routing_state'], unique=False)
    with op.batch_alter_table('reports') as batch_op:
        batch_op.create_foreign_key('fk_reports_routed_rule', 'organization_rules', ['routed_rule_id'], ['id'])
    op.add_column('sessions', sa.Column('csrf_token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'csrf_token')
    with op.batch_alter_table('reports') as batch_op:
        batch_op.drop_constraint('fk_reports_routed_rule', type_='foreignkey')
    op.drop_index(op.f('ix_reports_routing_state'), table_name='reports')
    op.drop_column('reports', 'human_confirmed')
    op.drop_column('reports', 'processing_error')
    op.drop_column('reports', 'processing_state')
    op.drop_column('reports', 'routed_rule_id')
    op.drop_column('reports', 'routing_state')
    op.drop_column('report_ai_analysis', 'success')
    op.drop_column('report_ai_analysis', 'duration_ms')
    op.drop_column('report_ai_analysis', 'input_kind')
    op.drop_column('report_ai_analysis', 'analyzer')
    # ### end Alembic commands ###
